#!/bin/bash
set -e -u

# Global Variables
VERSION="1.0.0"
REPOS=()
REPO_LEN=0
REPO_LIST="REPO_LIST.txt"
PKG_DIR="./sources/"        # Install Directory
TIME_OUT="10"               # Connection timeout
MAX_TIMEOUT="300"           # Full curl timeout
SUCCESS_URLS=()             # Array of program urls
SUCCESS_PATCH=()            # Array of patch urls
MD5SUMS="$PKG_DIR/md5sums"  # Checksum list for LFS Packages
LFS_CHECKSUM="https://www.linuxfromscratch.org/lfs/view/stable/md5sums"
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0"

# CLI Args
FORCE_SORT=0
NO_PATCH=0

# Colors and shit
TXT_BOLD='\033[1m'
TXT_END='\033[0m'

test_repo_speed() {
    # Test download speed of a repository
    local url="$1"
    local start_time=$(date +%s.%N)

    curl -fsSL "$url" \
        -A "$USER_AGENT" \
        --connect-timeout "$TIME_OUT" \
        --max-time 10 \
        -o /dev/null \
        -w '%{time_total}' 2>/dev/null || echo "999"
}

load_repos() {
    local skip_sort=0

    while IFS= read -r line; do
        # if any comment in the REPO_LIST contains '# --lock' it will not auto-sort.
        if [[ "$line" == *"# --lock"* ]] || [[ "" == *"#--lock"* ]]; then
            skip_sort=1
            continue
        fi

        if [[ "$line" == \#* ]] || [[ -z "$line" ]]; then
            :
        else
            REPOS+=("$line")
        fi
    done < "$REPO_LIST"

    REPO_LEN=${#REPOS[@]}
    local repo_prompt="repo"

    if [ "$REPO_LEN" -gt 1 ]; then
        repo_prompt="${repo_prompt}s"
    fi

    echo -e "${TXT_BOLD}Loaded repository list to memory ...${TXT_END} [$REPO_LEN $repo_prompt]"

    # Sort repos by speed
    if [ "$REPO_LEN" -gt 1 ]; then
        if [ "$skip_sort" -eq 0 ] || [ "$FORCE_SORT" -eq 1 ]; then
            echo -e "${TXT_BOLD}Testing repository speeds...${TXT_END}"

            local -a repo_speed_pairs
            for repo in "${REPOS[@]}"; do
                local speed=$(test_repo_speed "$repo")
                echo -e "  $repo ... ${TXT_BOLD}[${speed:0:5}s]${TXT_END}"
                repo_speed_pairs+=("$repo|$speed")
            done

            IFS=$'\n' repo_speed_pairs=($(sort -t'|' -k2 -n <<<"${repo_speed_pairs[*]}"))
            unset IFS

            REPOS=()
            for pair in "${repo_speed_pairs[@]}"; do
                REPOS+=("${pair%|*}")
            done

            echo -e "${TXT_BOLD}Repositories sorted by speed${TXT_END} - fastest first"

            # Write sorted list to file
            write_sorted_repos
        elif [ "$skip_sort" -eq 1 ]; then
            echo -e "${TXT_BOLD}Repository sorting locked${TXT_END} - using list as-is"
        fi
    elif [ "$REPO_LEN" -eq 0 ]; then
        echo -e "${TXT_BOLD}[Error]:${TXT_END} There are no repositories in $REPO_LIST"
        exit 1
    fi
}

write_sorted_repos() {
    # Write the sorted repos to the list and lock it
    local temp_file="${REPO_LIST}.tmp"

    local content="# Repositories soirted by fastest download speed\n"
    content+="# This file is locked, remove any line with '# --lock' to to re-test and re-sort\n"
    echo -e "$content" > "$temp_file"

    for repo in "${REPOS[@]}"; do
        echo "$repo" >> "$temp_file"
    done

    # Overwrite original
    mv "$temp_file" "$REPO_LIST"
    echo -e "${TXT_BOLD}Updated $REPO_LIST with sorted repositories...${TXT_END}"
}

pkg_search() {
    # Search for a single package
    local pkg="$1"
    local path=""

    echo -e "\n${TXT_BOLD}Searching for $pkg...${TXT_END}"

    for repo in "${REPOS[@]}"; do
        path=$(curl -fsSL "$repo" --connect-timeout "$TIME_OUT" \
            -A "$USER_AGENT" \
            | grep -oE "$pkg[^\"]*\.tar\.[^\" ]+" \
            | head -n 1)

        if [ -n "$path" ]; then
            SUCCESS_URLS+=("$repo$path")
            echo -e "  $repo$path ... ${TXT_BOLD}[FOUND]${TXT_END}"
        else
            echo -e "  $repo ... ${TXT_BOLD}[NOT FOUND]${TXT_END}"
        fi
    done

    if [ "${#SUCCESS_URLS[@]}" -eq 0 ]; then
        if [ "$REPO_LEN" -gt 1 ]; then
            local repo_prompt="repositories"
        else
            local repo_prompt="repository"
        fi

        echo -e "${TXT_BOLD}[Error]:${TXT_END} \"$pkg\" was not found in $REPO_LEN $repo_prompt..."
        return 1
    fi

    # Ask download to do it's job
    if in_sumlist "$path"; then
        if ! file_exists "$path"; then
            if download_pkg "$path" "pkg"; then
                success "$path" "pkg"
            else
                echo -e "Unable to download $path after trying all available mirrors."
                exit 1
            fi
        fi
    else
        echo -e "${TXT_BOLD}[Error]:${TXT_END} $path not in official LFS package list - aborting"
        exit 1
    fi
}

patch_search() {
    # Search for a single patch
    local name="$1"
    local path=""

    echo -e "\n${TXT_BOLD}Searching for $name Patch...${TXT_END}"

    for repo in "${REPOS[@]}"; do
        path=$(curl -fsSL "$repo" --connect-timeout "$TIME_OUT" \
            -A "$USER_AGENT" \
            | grep -oE "$name[^\"]*\.patch" \
            | head -n 1)

        if [ -n "$path" ]; then
            SUCCESS_PATCH+=("$repo$path")
            echo -e "  $repo$path ... ${TXT_BOLD}[FOUND]${TXT_END}"
        else
            echo -e "  $repo ... ${TXT_BOLD}[NOT FOUND]${TXT_END}"
        fi
    done

    if [ "${#SUCCESS_PATCH[@]}" -eq 0 ]; then
        echo -e "${TXT_BOLD}[Note]:${TXT_END} No patches were found for $name (this may be normal)."
        return 0 # Most packages will not have patches
    fi

    # Ask download to do it's job
    if in_sumlist "$path"; then
        if ! file_exists "$path"; then
            if download_pkg "$path" "patch"; then
                success "$path" "patch"
            fi
        fi
    else
        echo -e "${TXT_BOLD}[Warning]:${TXT_END} Patch $path not in official LFS list - skipping"
        return 0 # Not Fatal for patches
    fi

    return 0 # Even a failure is a Success in some ways
}

file_exists() {
    # Check if a package has already been downloaded
    local name="$1"
    full_file=$(realpath "$PKG_DIR/$name")

    if [[ ! -f "$full_file" ]]; then
        echo -e "  Package [$name] does not exist in: $PKG_DIR"
        return 1
    else
        file_size_bytes=$(wc -c < "$full_file")
        if [[ "$name" == *".patch" ]]; then
            file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1024}")
            local measurement="KB"
        else
            file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1048576}")
            local measurement="MB"
        fi

        NO_PATCH=1
        echo -e "\n${TXT_BOLD}Package [$name] already exists in:${TXT_END} $PKG_DIR\n  Size: $file_size $measurement\n  Location: $full_file"
        return 0
    fi
}

download_pkg() {
    # Download a single package
    # Note: If the download passes the timeout it tries the next successful link
    local name="$1"
    local filetype="$2"
    local idx=0

    if [[ "$filetype" == "pkg" ]]; then
        local -a url_list=("${SUCCESS_URLS[@]}")
    elif [[ "$filetype" == "patch" ]]; then
        local -a url_list=("${SUCCESS_PATCH[@]}")
    fi

    for pkg_url in "${url_list[@]}"; do
        echo -e "\n${TXT_BOLD}Downloading:${TXT_END} $name\n  From: $pkg_url"

        if curl -fsSL "$pkg_url" \
            -A "$USER_AGENT" \
            -o "$PKG_DIR/$name" \
            --max-time "$MAX_TIMEOUT"; then

            if check_sums "$name"; then
                return 0 # Success
            else
                echo -e "${TXT_BOLD}Checksum verification failed${TXT_END}, trying next mirror..."
                ((idx++))

                if [ "$idx" -eq "${#url_list[@]}" ]; then
                    return 1 # All mirrors (and checksums) failed
                fi
                continue
            fi
        else
            local exit_code="$?"
            echo -e "  Download failed with exit code $exit_code"

            # Clean up failed downloads
            clean_up "$name"
            ((idx++))

            if [ "$idx" -eq "${#url_list[@]}" ]; then
                return 1 # All mirrors failed
            fi
        fi
    done

    return 1 # Fallback
}

verify_checksum() {
    local filename="$1"
    local expected_hash="$2"

    if [[ ! -f "$PKG_DIR/$filename" ]]; then
        echo -e "File Not Found: $filename"
        return 1
    fi

    local actual_hash=$(md5sum "$PKG_DIR/$filename" | awk '{print $1}')

    if [[ "$expected_hash" == "$actual_hash" ]]; then
        echo -e "  Checksum verified!"
        return 0
    else
        local prompt="  Checksum failed to verify: $filename\n"
        prompt+="  - Expected: $expected_hash\n"
        prompt+="  - Received: $actual_hash"
        echo -e "$prompt"
        return 1
    fi
}

in_sumlist() {
    # Check if a file pulled from repository is in checksum list
    local name="$1"

    if [ -z "$MD5SUMS" ] || [ ! -f "$MD5SUMS" ]; then
        curl "$LFS_CHECKSUM" -o "$PKG_DIR/md5sums"
    fi

    while IFS= read -r line; do
        [ -z "$line" ] || [[ "$line" == \#* ]] && continue

        local filename=$(echo "$line" | awk '{$1=""; print $0}' | xargs)
        if [[ "$filename" == "$name" ]]; then
            echo -e "  $name found in md5sums list"
            return 0 # Found in list
        fi
    done < "$MD5SUMS"

    echo -e "  ${TXT_BOLD}$name not found in md5sums list${TXT_END} - skipping download"
    return 1 # Not Found
}

check_sums() {
    # Verify the package matches the checksum
    local name="$1"
    local found=0 # boolean

    if [ -z "$MD5SUMS" ] || [ ! -f "$MD5SUMS" ]; then
        curl "$LFS_CHECKSUM" -o "$PKG_DIR/md5sums"
    fi

    while IFS= read -r line; do
        [[ -z "$line" ]] || [[ "$line" == \#* ]] && continue

        if [[ "$line" =~ "$name" ]]; then
            found=1
            local expected_hash=$(echo -e "$line" | awk '{print $1}')
            local filename=$(echo -e "$line" | awk '{$1=""; print $0}' | xargs)

            if [[ "$filename" == *".patch" ]]; then
                echo -e "\n${TXT_BOLD}Verifying patch:${TXT_END} $filename"
                if ! verify_checksum "$filename" "$expected_hash"; then
                    clean_up "$filename"
                    return 1 # Checksum failed
                fi
            else
                echo -e "\n${TXT_BOLD}Verifying program:${TXT_END} $filename"
                if ! verify_checksum "$filename" "$expected_hash"; then
                    clean_up "$filename"
                    return 1 # Checksum failed
                fi
            fi
        fi
    done < "$MD5SUMS"

    # Make sure file is found in MD5 before saving to the disk.
    if [ "$found" -eq 0 ]; then
        echo -e "[Error]: $name not found in md5sum list - cannot verify integrity"
        clean_up "$name"
        return 1
    fi

    return 0 # All checksums passed
}

clean_up() {
    # Clean up any files made from failed download attempts
    local name="$1"
    rm -rfv "$PKG_DIR/$name"
}

failure() {
    # Tell the user a file couldn't be downloaded!
    local name="$1"
    tries=$((${#SUCCESS_URLS} - 1)) # Number of URLS attempted
    echo -e "Unable to download $name (after $tries tries)"
}

success() {
    local path="$1"
    local filetype="$2"
    local full_file=$(realpath "$PKG_DIR/$path")
    local file_size_bytes=$(wc -c < "$full_file")
    local prompt="\n${TXT_BOLD}Successfully downloaded:${TXT_END} $path!\n"

    if [[ "$filetype" == "patch" ]]; then
        local file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1024}")
        prompt+="  Size: $file_size KB\n"
    elif [[ "$filetype" == "pkg" ]]; then
        local file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1048576}")
        prompt+="  Size: $file_size MB\n"
    fi

    prompt+="  Location: $full_file"
    echo -e "$prompt"
}

help_info() {
    local prompt="Usage: spkg [OPTION] <package>..."
    prompt+="\nEasily download a specific package from a repository."
    prompt+="\n\n  -n, --no-patch\tdo not check for patches"
    prompt+="\n  -f, --force-sort\tforce the downloader to re-sort the repositories"
    prompt+="\n  -p, --force-patch\tforce the downloader to check for patches"
    prompt+="\n\n  -h, --help\t\tdisplay this help and exit"
    prompt+="\n  -v, --version\t\toutput version information and exit"
    prompt+="\n\nReport bugs to: https://github.com/RileyMeta/spkgs-lfs/pulls"
    echo -e "$prompt"
}

version_info() {
    local prompt="spkg (Simple Package) $VERSION"
    prompt+="\nCopyright (C) 2025 Riley Ava."
    prompt+="\nLicense MPL-2: Mozilla Public License 2.0 <https://www.mozilla.org/en-US/MPL/2.0/>."
    prompt+="\nThis is free software: you are free to change and redistribute it."
    prompt+="\nThere is NO WARRANTY, to the extent permitted by law."
    prompt+="\n\nWritten by Riley Ava."
    echo -e "$prompt"
}

main() {
    local name="$1"     # Name of the package

    if [[ "$1" == --* || "$1" == -* ]]; then
        if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
            help_info
            exit 0
        elif [ "$1" == "--version" ] || [ "$1" == "-v" ]; then
            version_info
            exit 0
        fi

        if [[ "$1" ==  "--no-patch" || "$1" == "-n" ]]; then
            NO_PATCH=1
        elif [[ "$1" == "--force-sort" || "$1" == "-f" ]]; then
            FORCE_SORT=1
        elif [[ "$1" == "--force-patch" || "$1" == "-p" ]]; then
            FORCE_PATCH=1
        else
            echo -e "$name is not recognized.\nUse '--help' to see all available options."
            exit 1
        fi

        shift
        name="${1:-}"

        if [[ -z "$name" ]]; then
            echo -e "Usage: spkg [options] <package>"
            exit 1
        fi
    else
        name="$1"
    fi

    [[ ! -d "$PKG_DIR" ]] && { mkdir -pv "$PKG_DIR"; }

    if [ ! -f "$REPO_LIST" ]; then
        local prompt="# Use # to comment out repos\n# Add repo urls below"
        echo -e "$prompt" > "$REPO_LIST"
        echo -e "$REPO_LIST created in $(realpath $REPO_LIST)"
        exit 1
    fi

    load_repos
    pkg_search "$name"

    if [ "$NO_PATCH" != 1 ] || [ "$FORCE_PATCH" != 0 ]; then
        patch_search "$name"
    fi
}

main "$@"
