#!/bin/bash
set -e -u

REPOS=()
REPO_LEN=0
REPO_LIST="REPO_LIST.txt"
PKG_DIR="./sources/"        # Install Directory
TIME_OUT="10"               # Connection timeout
MAX_TIMEOUT="300"           # Full curl timeout
SUCCESS_URLS=()             # Array of program urls
SUCCESS_PATCH=()            # Array of patch urls
MD5SUMS="$PKG_DIR/md5sums"  # Checksum list for LFS Packages
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0"

load_repos() {
    while IFS= read -r line; do
        if [[ "$line" == \#* ]] || [[ -z "$line" ]]; then
            :
        else
            REPOS+=("$line")
        fi
    done < "$REPO_LIST"

    REPO_LEN=${#REPOS[@]}
    local repo_prompt="repo"

    if [ "$REPO_LEN" -gt 1 ]; then
        repo_prompt="${repo_prompt}s"
    fi

    echo -e "Loaded repository list [$REPO_LEN $repo_prompt] to memory..."
}

pkg_search() {
    # Search for a single package
    local pkg="$1"
    local path=""

    echo -e "Searching for $pkg..."

    for repo in "${REPOS[@]}"; do
        path=$(curl -fsSL "$repo" --connect-timeout "$TIME_OUT" \
            -A "$USER_AGENT" \
            | grep -oE "$pkg[^\"]*\.tar\.[^\" ]+" \
            | head -n 1)

        if [ -n "$path" ]; then
            SUCCESS_URLS+=("$repo$path")
            echo -e "$repo$path ... [FOUND]"
        else
            echo -e "$repo ... [NOT FOUND]"
        fi
    done

    if [ "${#SUCCESS_URLS[@]}" -eq 0 ]; then
        if [ "$REPO_LEN" -gt 1 ]; then
            local repo_prompt="repositories"
        else
            local repo_prompt="repository"
        fi

        echo -e "[Error]: \"$pkg\" was not found in $REPO_LEN $repo_prompt..."
        return 1
    fi

    # Ask download to do it's job
    if ! file_exists "$path"; then
        if download_pkg "$path" "pkg"; then
            success "$path" "pkg"
        else
            echo -e "Unable to download $path after trying all available mirrors."
            exit 1
        fi
    fi
}

patch_search() {
    # Search for a single patch
    local name="$1"
    local path=""

    echo -e "Searching for $name Patch..."

    for repo in "${REPOS[@]}"; do
        path=$(curl -fsSL "$repo" --connect-timeout "$TIME_OUT" \
            -A "$USER_AGENT" \
            | grep -oE "$name[^\"]*\.patch" \
            | head -n 1)

        if [ -n "$path" ]; then
            SUCCESS_PATCH+=("$repo$path")
            echo -e "  $repo$path ... [FOUND]"
        else
            echo -e "  $repo ... [NOT FOUND]"
        fi
    done

    if [ "${#SUCCESS_PATCH[@]}" -eq 0 ]; then
        echo -e "Note: No patches were found for $name (this may be normal)."
        return 0 # Most packages will not have patches
    fi

    # Ask download to do it's job
    if ! file_exists "$path"; then
        if download_pkg "$path" "patch"; then
            success "$path" "patch"
        fi
    fi

    return 0 # Even a failure is a Success in some ways
}

file_exists() {
    # Check if a package has already been downloaded
    local name="$1"
    full_file=$(realpath "$PKG_DIR/$name")

    if [[ ! -f "$full_file" ]]; then
        echo -e "  Package [$name] does not exist in: $PKG_DIR"
        return 1
    else
        file_size_bytes=$(wc -c < "$full_file")
        if [[ "$name" == *".patch" ]]; then
            file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1024}")
            local measurement="KB"
        else
            file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1048576}")
            local measurement="MB"
        fi
        echo -e "Package [$name] already exists in: $PKG_DIR\n  Size: $file_size $measurement\n  Location: $full_file"
        return 0
    fi
}

download_pkg() {
    # Download a single package
    # Note: If the download passes the timeout it tries the next successful link
    local name="$1"
    local filetype="$2"
    local idx=0

    if [[ "$filetype" == "pkg" ]]; then
        local -a url_list=("${SUCCESS_URLS[@]}")
    elif [[ "$filetype" == "patch" ]]; then
        local -a url_list=("${SUCCESS_PATCH[@]}")
    fi

    for pkg_url in "${url_list[@]}"; do
        echo -e "Downloading: $name\n  From: $pkg_url"

        if curl -fsSL "$pkg_url" \
            -A "$USER_AGENT" \
            -o "$PKG_DIR/$name" \
            --max-time "$MAX_TIMEOUT"; then

            if check_sums "$name"; then
                return 0 # Success
            else
                echo -e "Checksum verification failed, trying next mirror..."
                ((idx++))

                if [ "$idx" -eq "${#url_list[@]}" ]; then
                    return 1 # All mirrors (and checksums) failed
                fi
                continue
            fi
        else
            local exit_code="$?"
            echo -e "Download failed with exit code $exit_code"

            # Clean up failed downloads
            clean_up "$name"
            ((idx++))

            if [ "$idx" -eq "${#url_list[@]}" ]; then
                return 1 # All mirrors failed
            fi
        fi
    done

    return 1 # Fallback
}

verify_checksum() {
    local filename="$1"
    local expected_hash="$2"

    if [[ ! -f "$PKG_DIR/$filename" ]]; then
        echo -e "File Not Found: $filename"
        return 1
    fi

    local actual_hash=$(md5sum "$PKG_DIR/$filename" | awk '{print $1}')

    if [[ "$expected_hash" == "$actual_hash" ]]; then
        echo -e "  Checksum verified: $filename"
        return 0
    else
        local prompt="  Checksum failed to verify: $filename\n"
        prompt+="  - Expected: $expected_hash\n"
        prompt+="  - Received: $actual_hash"
        echo -e "$prompt"
        return 1
    fi
}

check_sums() {
    # Verify the package matches the checksum
    local name="$1"
    local lfs_checksum="https://www.linuxfromscratch.org/lfs/view/stable/md5sums"
    local found=0 # boolean

    if [ -z "$MD5SUMS" ] || [ ! -f "$MD5SUMS" ]; then
        curl "$lfs_checksum" -o "$PKG_DIR/md5sums"
    fi

    while IFS= read -r line; do
        [[ -z "$line" ]] || [[ "$line" == \#* ]] && continue

        if [[ "$line" =~ "$name" ]]; then
            found=1
            local expected_hash=$(echo -e "$line" | awk '{print $1}')
            local filename=$(echo -e "$line" | awk '{$1=""; print $0}' | xargs)

            if [[ "$filename" == *".patch" ]]; then
                echo -e "Verifying patch: $filename"
                if ! verify_checksum "$filename" "$expected_hash"; then
                    clean_up "$filename"
                    return 1 # Checksum failed
                fi
            else
                echo -e "Verifying program: $filename"
                if ! verify_checksum "$filename" "$expected_hash"; then
                    clean_up "$filename"
                    return 1 # Checksum failed
                fi
            fi
        fi
    done < "$MD5SUMS"

    # Make sure file is found in MD5 before saving to the disk.
    if [ "$found" -eq 0 ]; then
        echo -e "[Error]: $name not found in md5sum list - cannot verify integrity"
        clean_up "$name"
        return 1
    fi

    return 0 # All checksums passed
}

clean_up() {
    # Clean up any files made from failed download attempts
    local name="$1"
    rm -rfv "$PKG_DIR/$name"
}

failure() {
    # Tell the user a file couldn't be downloaded!
    local name="$1"
    tries=$((${#SUCCESS_URLS} - 1)) # Number of URLS attempted
    echo -e "Unable to download $name (after $tries tries)"
}

success() {
    local path="$1"
    local filetype="$2"
    local full_file=$(realpath "$PKG_DIR/$path")
    local file_size_bytes=$(wc -c < "$full_file")
    local prompt="Successfully downloaded $path!\n"

    if [[ "$filetype" == "patch" ]]; then
        local file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1024}")
        prompt+="  Size: $file_size KB\n"
    elif [[ "$filetype" == "pkg" ]]; then
        local file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1048576}")
        prompt+="  Size: $file_size MB\n"
    fi

    prompt+="  Location: $full_file"
    echo -e "$prompt"
}

main() {
    local name="$1"     # Name of the package

    [[ ! -d "$PKG_DIR" ]] && { mkdir -pv "$PKG_DIR"; }
    [[ -z "$name" ]] && { echo -e "Usage: spkg <package>"; return 1; }

    if [ ! -f "$REPO_LIST" ]; then
        local prompt="# Use # to comment out repos\n# Add repo urls below"
        echo -e "$prompt" > "$REPO_LIST"
        echo -e "$REPO_LIST created in $(realpath $REPO_LIST)"
        exit 1
    fi

    load_repos
    pkg_search "$name"
    patch_search "$name"
}

main "$@"
