#!/bin/bash
set -e

REPOS=("https://lfs.gnlug.org/pub/lfs/lfs-packages/12.4/")
REPO_LIST="REPO_LIST.txt"
PKG_DIR="./sources/"
TIME_OUT="10" # 10 second connection timout 
MAX_TIMEOUT="300" # 5 minute timeout
SUCCESS_URLS=() # Array of urls that connected successfully
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0"

load_repos() {
    # Load the textfile of repos to array
    while IFS= read -r line; do
        if [[ "$line" == \#* ]] || [[ -z "$line" ]]; then
            :
        else
            REPOS+=("$line")
        fi
    done < "$REPO_LIST"
}

pkg_search() {
    # Search for a single package
    # Param1: Name of package in string form
    local pkg=$1

    for repo in "${REPOS[@]}"; do
        path=$(curl -fsSL "$repo" --connect-timeout "$TIME_OUT" \
            -A "$USER_AGENT" \
            | grep -oE "$pkg[^\"]*\.tar\.[^\" ]+" \
            | head -n 1)

        if [ -n "$path" ]; then
            SUCCESS_URLS+=("$repo$path")
            echo -e "${SUCCESS_URLS[@]} ... [FOUND]"
        else
            echo -e "${repo}${path} ... [NOT FOUND!]"
        fi
    done

    # Ask download to do it's job
    download_pkg "$path"
}

download_pkg() {
    # Download a single package
    # Param1: The name of the file
    # Note: If the download passes the timeout it tries the next successful link 
    name=$1
    idx=0

    for pkg_url in "${SUCCESS_URLS[@]}"; do
        echo -e "Downloading: $name\n  From: $pkg_url"

        if curl -fsSL "$pkg_url" \
            -A "$USER_AGENT" \
            -o "$PKG_DIR/$name" \
            --max-time "$MAX_TIMEOUT"; then
            
            success "$name"
            return 0
        else
            local exit_code=$?
            echo -e "Download failed with exit code $exit_code"

            # Clean up failed downloads
            clean_up "$name"
            ((idx++))

            if [ "$idx" -eq "$((${#SUCCESS_URLS} - 1))" ]; then
                failure "$name"
            fi
        fi
    done
}

clean_up() {
    # Clean up any files made from failed download attempts
    # Param1: Full name of the program
    name=$1
    rm -rfv "$PKG_DIR/$name"
}

failure() {
    # Tell the user a file couldn't be downloaded!
    # Param1: Full name of the program
    name=$1
    tries=$((${#SUCCESS_URLS} - 1)) # Number of URLS attempted
    echo -e "Unable to download $name (after $tries tries)"
    exit 1
}

success() {
    # Tell the user it's been downloaded successfully!
    # Param1: Full name of the program
    name=$1
    echo -e "Successfully downloaded $name!\n  Location: $(realpath "$PKG_DIR/$name")"
    exit 0
}

main() {
    # Initialize the Package Downloader
    # Param1: The name of the package
    local name="$1"

    [[ ! -d "$PKG_DIR" ]] && { mkdir -pv "$PKG_DIR"; }
    [[ -z "$name" ]] && { echo "Usage: spkg <package>"; return 1; }

    if [ ! -f "$REPO_LIST" ]; then
        local prompt="# Use # to comment out repos\n# Add repo urls below"
        echo -e "$prompt" > "$REPO_LIST"
        echo -e "$REPO_LIST created in $(realpath $REPO_LIST)"
        exit 1
    fi

    load_repos "$REPO_LIST"
    echo -e "Repository list [${#REPOS[@]}] loaded to memory..."

    echo "Searching for $name..."
    pkg_search "$name"
}

main "$@"
